dataset:
  chexpert_labels : [
    'Atelectasis',
    'Cardiomegaly', 
    'Consolidation', 
    'Edema', 
    'Enlarged Cardiomediastinum',
    'Fracture',
    'Lung Lesion',
    'Lung Opacity',
    'No Finding',
    'Pleural Effusion',
    'Pleural Other',
    'Pneumonia',
    'Pneumothorax',
    'Support Devices'
  ]
  batch_size : 8
  input_size : 224
  data_imputation : "zeros"
  train_size : 0.8
  val_size : 0.1
  test_size : 0.1
  num_wokers : 4