dataset:
  chexpert_labels : [
    'Atelectasis',
    'Cardiomegaly', 
    'Consolidation', 
    'Edema', 
    'Enlarged Cardiomediastinum',
    'Fracture',
    'Lung Lesion',
    'Lung Opacity',
    'No Finding',
    'Pleural Effusion',
    'Pleural Other',
    'Pneumonia',
    'Pneumothorax'
  ]
  batch_size : 16
  input_size : 224 #224 #256 #224
  data_imputation : "zeros"
  val_size : 0.1
  test_size : 0.1
  num_workers : 16
  paired: False
  channels: 3
  use_all_images: False
  num_images: 1


image_generator:
  learning_rate: 0.001
  optimizer: 'Adam' # AdamW
  report_encoder_model : "cgan"
  generator_layer_size : [256, 512, 1024]
  z_size : 100
  weight_decay: 0.0001
  decay_epochs : 5
  beta1: 0.9
  beta2: 0.999
  monitor: 'val_loss'
  ddpm_beta1 : 1e-4
  ddpm_beta2 : 0.02
  ddpm_drop_prob : 0.1
  n_feat : 256
  n_T : 400


image_discriminator:
  learning_rate: 0.001
  optimizer: 'Adam' # AdamW
  weight_decay: 0.0001
  decay_epochs : 5
  beta1: 0.5
  beta2: 0.999
  monitor: 'val_loss'
  channels: 3
  img_height: 224
  img_width: 224


report_generator:
  learning_rate: 0.001
  optimizer: 'Adam' # AdamW
  weight_decay: 0.0001
  decay_epochs : 5
  beta1: 0.9
  beta2: 0.999
  monitor: 'val_loss'
  image_encoder_model: 'BioVil' #'ARK' #"BioVil"
  classification_head_hidden1: 2048
  classification_head_hidden2: 512
  dropout_prob: 0.5
  embedding_size : 512 #128 for global embedding


report_discriminator:
  learning_rate: 0.001
  optimizer: 'Adam' # AdamW
  weight_decay: 0.0001
  decay_epochs : 5
  beta1: 0.9
  beta2: 0.999
  model : 'discriminator' # discriminator


trainer :
  num_classes : 13
  lambda_cycle: 10
  seed : 42
  buffer_size : 300
  check_val_every_n_epochs: 1
  n_epoch: 10000
  threshold : 0.5
  log_images_steps: 100
  gen_threshold: 0.25
  disc_threshold: 0.20
  visualize: True
  save_images: False








