dataset:
  chexpert_labels : [
    'Atelectasis',
    'Cardiomegaly', 
    'Consolidation', 
    'Edema', 
    'Enlarged Cardiomediastinum',
    'Fracture',
    'Lung Lesion',
    'Lung Opacity',
    'No Finding',
    'Pleural Effusion',
    'Pleural Other',
    'Pneumonia',
    'Pneumothorax'
  ]
  batch_size : 1
  sample_size : -1
  input_size : 224
  data_imputation : "zeros"
  val_size : 0.1
  test_size : 0.1
  num_workers : 4
  paired: False


image_generator:
  model : "ddpm"
  learning_rate: 0.001
  optimizer: 'Adam' # AdamW
  generator_layer_size : [256, 512, 1024]
  z_size : 100
  weight_decay: 0.001
  decay_epochs : 5
  beta: 0.9
  ddpm_beta1 : 1e-4
  ddpm_beta2 : 0.02
  ddpm_drop_prob : 0.1
  n_feat : 128
  n_T : 400
  consistency_loss : "biovil_t"


image_discriminator:
  learning_rate: 0.0001
  optimizer: 'Adam' # AdamW
  weight_decay: 0.0001
  decay_epochs : 5
  beta: 0.9
  channels: 3
  img_height: 224
  img_width: 224
  adversarial_loss : 'MSE'


report_generator:
  model : 'biovil_t'
  learning_rate: 0.001
  optimizer: 'Adam' # AdamW
  weight_decay: 0.0001
  decay_epochs : 5
  beta: 0.9
  classification_head_hidden1: 512
  classification_head_hidden2: 256
  dropout_prob: 0.5
  consistency_loss : 'BCE'
  embedding_size : 128


report_discriminator:
  base : 'discriminator_network'
  learning_rate: 0.0001
  optimizer: 'Adam' # AdamW
  weight_decay: 0.0001
  decay_epochs : 5
  beta: 0.9
  adversarial_loss : 'MSE'



trainer :
  num_classes : 13
  lambda_cycle_loss: 10
  seed : 42
  buffer_size : 300
  check_val_every_n_epochs: 1
  n_epoch: 5
  threshold : 0.5
  accumulated_batches : 5 # number of batches to accumulate before optimizing (decide number of batches to calculate loss)
  metrics : "KLDivergence"
  log_images_steps: 100
  log_metrics_step : 10






