dataset:
  chexpert_labels : [
    'Atelectasis',
    'Cardiomegaly', 
    'Consolidation', 
    'Edema', 
    'Enlarged Cardiomediastinum',
    'Fracture',
    'Lung Lesion',
    'Lung Opacity',
    'No Finding',
    'Pleural Effusion',
    'Pleural Other',
    'Pneumonia',
    'Pneumothorax'
  ]
  batch_size : 8
  input_size : 256 #256 #224 #256 #224
  data_imputation : "zeros"
  val_size : 0.1
  test_size : 0.1
  num_workers : 4
  paired: True
  channels: 3
  use_all_images: False
  num_images: 10000


image_generator:
  learning_rate: 0.0001
  optimizer: 'Adam' # AdamW
  scheduler: 'ReduceLROnPlateau' # cosine, exponential, polynomial
  report_encoder_model : "ddpm"
  generator_layer_size : [256, 512, 1024]
  z_size : 100
  weight_decay: 0.0001
  decay_epochs : 5
  beta1: 0.9
  beta2: 0.999
  monitor: 'val_loss'
  ddpm_beta1 : 1e-4
  ddpm_beta2 : 0.02
  ddpm_drop_prob : 0.1
  n_feat : 256
  n_T : 400
  NF: 64


image_discriminator:
  learning_rate: 0.001
  optimizer: 'Adam' # AdamW
  scheduler: 'ReduceLROnPlateau' # cosine, exponential, polynomial
  weight_decay: 0.0001
  decay_epochs : 5
  beta1: 0.9
  beta2: 0.999
  monitor: 'val_loss'
  channels: 3
  img_height: 224
  img_width: 224


report_generator:
  learning_rate: 0.001
  optimizer: 'Adam' # AdamW
  scheduler: 'ReduceLROnPlateau' # cosine, exponential, polynomial
  weight_decay: 0.0001
  decay_epochs : 5
  beta1: 0.9
  beta2: 0.999
  monitor: 'val_loss'
  image_encoder_model: "BioVil"
  classification_head_hidden1: 512
  classification_head_hidden2: 256
  dropout_prob: 0.5
  embedding_size : 128


report_discriminator:
  learning_rate: 0.001
  optimizer: 'Adam' # AdamW
  scheduler: 'ReduceLROnPlateau' # cosine, exponential, polynomial
  weight_decay: 0.0001
  decay_epochs : 5
  beta1: 0.9
  beta2: 0.999


trainer :
  num_classes : 13
  lambda_cycle_loss: 10
  seed : 42
  buffer_size : 300
  check_val_every_n_epochs: 1
  n_epoch: 10000
  threshold : 0.5
  accumulated_batches : 5 # number of batches to accumulate before optimizing (decide number of batches to calculate loss)
  metrics : "KLDivergence"
  log_images_steps: 100
  gen_training_threshold: 0.25
  disc_training_threshold: 0.20
  visualize: True
  save_images: True








