dataset:
  chexpert_labels : [
    'Atelectasis',
    'Cardiomegaly', 
    'Consolidation', 
    'Edema', 
    'Enlarged Cardiomediastinum',
    'Fracture',
    'Lung Lesion',
    'Lung Opacity',
    'No Finding',
    'Pleural Effusion',
    'Pleural Other',
    'Pneumonia',
    'Pneumothorax'
  ]
  batch_size : 16
  input_size : 224
  data_imputation : "zeros"
  train_size : 0.8
  test_size : 0.1
  num_workers : 4
  paired: True


model:
  seed : 42
  num_classes : 13
  embedding_size : 128
  lerning_rate : 0.0001
  loss : 'KLDivergence' # CosineSimilarity, KLDivergence, Wasserstein, JSDivergence, Occurences, MSE
  learning_rate: 0.0001
  optimizer : 'Adam' # AdamW
  scheduler : 'ReduceLROnPlateau' # cosine, exponential, polynomial
  weight_decay : 0.001
  accumulated_batches : 5 # number of batches to accumulate before optimizing (decide number of batches to calculate loss)
  n_epoch: 5
  threshold : 0.5
  image_encoder_model: "BioVil"
  check_val_every_n_epochs: 1
  monitor : 'val_loss'

