dataset:
  chexpert_labels : [
    'Atelectasis',
    'Cardiomegaly', 
    'Consolidation', 
    'Edema', 
    'Enlarged Cardiomediastinum',
    'Fracture',
    'Lung Lesion',
    'Lung Opacity',
    'No Finding',
    'Pleural Effusion',
    'Pleural Other',
    'Pneumonia',
    'Pneumothorax',
    'Support Devices'
  ]
  batch_size : 32
  input_size : 224
  data_imputation : "zeros"
  train_size : 0.8
  test_size : 0.1
  num_workers : 4


learning_rate: 0.0001
check_val_every_n_epochs: 1
max_epochs: 5
image_encoder_model: "BioVil"
num_classes_img_encoder: 14
